<?php $_columnCount=2;?>
<div id="home-new-products">
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
<h2><?php echo $this->__('New Products') ?></h2>
    <?php $i=0; foreach ($_products->getItems() as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <div class="products-row">
        <?php endif ?>
            <div class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135) ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h3>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            </div>
        <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
        </div>
        <?php endif ?>
    <?php endforeach; ?>
<?php endif; ?>
</div>
