<?php if ($this->_session->getId() > 0): ?>
<div class="base-livechat livechat-box mini-livechat left" id="chat_<?php echo $this->_session->getId(); ?>" style="display: block;">
	<span style="float: right" class="close" onclick="javascript:OperatorCloseSession_<?php echo $this->_session->getId(); ?>();"></span><div class="head"><h4><?php echo $this->__('Session'); ?> #<?php echo $this->_session->getId(); ?></h4></div>
	<div class="content">
		<p id="livechat_messages_<?php echo $this->_session->getId(); ?>"></p>
	</div>
	<div class="actions">
		<input type="text" id="textmessage_<?php echo $this->_session->getId(); ?>" name="message" onKeyPress="javascript:LiveChatKeyPress_<?php echo $this->_session->getId(); ?>(event);">
        <img id="livechat_ajax_loader_<?php echo $this->_session->getId(); ?>" style="display: none;" src="<?php echo $this->getSkinUrl('images/livechat/ajax-loader.gif'); ?>">
		<div style="text-align: right;">
		
        <?php
		echo "<button class=\"form-button-alt add\" onclick=\"javascript:SendMessage_".$this->_session->getId()."();\">";
        ?>
        <span><?php echo $this->__('Send'); ?></span></button></div>
	</div>
</div>
<?php endif; ?>
<script language="javascript">
var chatupdater<?php echo $this->_session->getId(); ?> = new Ajax.PeriodicalUpdater(
																						'livechat_messages_<?php echo $this->_session->getId(); ?>',
																						urlUpdater,
																						{
																							method: 'post',
																							parameters: {sessionId: <?php echo $this->_session->getId(); ?>},
																							frequency: 20,
																							decay: 1
																						}
																					);

String.prototype.trim = function()
{
    return this.replace(/(?:^\s+|\s+$)/g, "");
}

function SendMessage_<?php echo $this->_session->getId(); ?>()
{
	var customermessage = document.getElementById('textmessage_<?php echo $this->_session->getId(); ?>').value.trim();
	document.getElementById('textmessage_<?php echo $this->_session->getId(); ?>').value = '';
	if (customermessage != '')
	{
		var img = document.getElementById('livachat_ajax_loader_<?php echo $this->_session->getId(); ?>');
		if (img != null)
		{
			img.style.display = 'inline';
		}
		var request = new Ajax.Updater(
			'livechat_messages_<?php echo $this->_session->getId(); ?>',
			urlSendMessage,
			{
			    method: 'post',
			    parameters: { sessionId: <?php echo $this->_session->getId(); ?>, message: customermessage },
			    onSuccess: function(transport, json) {
			        var img = document.getElementById('livechat_ajax_loader_<?php echo $this->_session->getId(); ?>');
			        if (img != null) {
			            img.style.display = 'none';
			        }
			    },
			    insertion: Insertion.Bottom
			}
		);
	}
}
function LiveChatKeyPress_<?php echo $this->_session->getId(); ?>(e) {
    if (e.keyCode == 13) {
        SendMessage_<?php echo $this->_session->getId(); ?>();
    }
}

function CloseChatBox_<?php echo $this->_session->getId() ?>()
{
	chatupdater<?php echo $this->_session->getId(); ?>.stop();
	var chat = document.getElementById('chat_<?php echo $this->_session->getId(); ?>');
	if (chat != null)
	{
		chat.style.display = 'none';
	}
}

function OperatorCloseSession_<?php echo $this->_session->getId() ?>()
{
	if (confirm('<?php echo $this->__('Are you sure ?'); ?>'))
	{
		new Ajax.Request(
			urlOperatorCloseSession,
			{
				method: 'post',
				parameters: {sessionId: <?php echo $this->_session->getId() ?>},
				onSuccess: function() { CloseChatBox_<?php echo $this->_session->getId() ?>(); }
			}
		);
	}
}
</script>