<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-livechat"><?php echo $this->__('Sessions Live'); ?></h3></td>
		<td class="a-right">
<?php 
$session = Mage::getSingleton('livechat/adminSession');
if ($session->getData('OperatorName') != null):
$refreshrate = (int)Mage::getStoreConfig('livechatconfiguration/general/adminrefreshrate', 0);
?>

<script language="javascript">
	var urlSendMessage = '<?php echo $this->urlSendMessage; ?>';
	var urlUpdater = '<?php echo $this->urlUpdater; ?>';
	var urlOperatorCloseSession = '<?php echo $this->urlOperatorCloseSession; ?>';
</script>
<script type="text/javascript">

function refresh (){window.location.replace('<?php echo $this->getUrl('*/*/index'); ?>');}


var livechatloginform = new varienForm('livechatloginloginform');
var pe = new PeriodicalExecuter(refresh, <?php echo $refreshrate; ?>);
</script>
<?php
else:
?>
<form name="livechatloginloginform" id="livechatloginloginform" method="post" action="<?php echo $this->getUrl('*/*/login'); ?>">
<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>">
<?php echo $this->__('Operator name'); ?> <input type="text" name="Login"><br />
<?php echo $this->__('Operator key'); ?> <input type="password" name="Key"><br />
<button class="form-button-alt save" onclick="javascript: livechatloginform.submit(); return false;"><span><?php echo $this->__('Log in'); ?></span></button>
</form>
<script type="text/javascript">
    var livechatloginform = new varienForm('livechatloginloginform');
</script>
<?php endif; ?>
</td>
</tr>
</table>
</div>