<!--<script type="text/javascript" src="https://getfirebug.com/firebug-lite-debug.js"></script>-->



<?php

function curPageURL() {

 $pageURL = 'http';

 if ($_SERVER["HTTPS"] == "on") {$pageURL .= "s";}

 $pageURL .= "://";

 if ($_SERVER["SERVER_PORT"] != "80") {

  $pageURL .= $_SERVER["SERVER_NAME"].":".$_SERVER["SERVER_PORT"].$_SERVER["REQUEST_URI"];

 } else {

  $pageURL .= $_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];

 }

 
 
 return $pageURL;

}

?>

<?php
// ********************   contact us Page Style by tracking URL  *************************
  if(curPageURL() =='http://thebedroom.com.au/contacts'){

?>

<style>

 
html body.contacts-contacts-index div.wrapper div.page div.main-container div.main div.col-main div.page-title {
border-bottom: 1px solid #CCCCCC;
margin: 5px 0 20px 10px !important;
overflow: hidden;
width: 567px !important;
}



</style>

<?php
	}
?>
<?php
// ********************   contact us Page Style by tracking URL  *************************
  if(curPageURL() =='https://staging.thebedroom.com.au:443/onestepcheckout'){

?>

<style>

 
.main {
  width: 100%;
}



</style>

<?php
	}
?>
<?php
// ********************   about us Page Style by tracking URL  *************************
  if(curPageURL() =='http://thebedroom.com.au/about-us'){

?>

<style>
.breadcrumbs
{
	display:none !important;
}

.std p { width:567px !important;}

h1 {
  line-height: 1.6;
}
 
</style>

<?php
}
?>


<?php
//echo curPageURL();
// ********************   Home Page Style by tracking URL  *************************
if(curPageURL() =='http://thebedroom.com.au' || curPageURL() =='http://thebedroom.com.au/'){

?>

<style>
html body.cms-index-index div.wrapper div.page div.main-container div.main div.col-left
{
	padding:5px 0 0 5px !important;		 			
}
 
 
 .block .block-content {
  border: 0 !important;
  
}
#specials{
	border-left: 1px solid silver;
		border-right: 1px solid silver;

	border-bottom: 1px solid silver;

	width:190px !important;
	margin-top: 8px
	}
	
	
</style>
<?php
}



?>


<div class="header-container">
    <div class="header">
        <div class="quick-access">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('phone')->toHtml() ?>
        	<?php //echo $this->getChildHtml('topLinks') ?>
            <?php echo $this->getChildHtml('topSearch') ?>
            <!--<p class="welcome-msg"><?php //echo $this->getWelcome()?></p>-->
            <?php echo $this->getChildHtml('store_language') ?>
        </div>
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img style="float:left" src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
        <?php echo $this->getChildHtml('topContainer'); ?>
        <div id="top-nav">
			<?php echo $this->getChildHtml('top_navigation'); ?>
		</div>
    </div>
</div>
        
        
 <style type="text/css">

div.totals 
{
    right: 345px !important;
}
.success-msg {
    display: block;
    position: relative;
    width: 499px;
}
	.messages{
		
    position: relative;
    left: 21px;

		}
		
		button.btn-checkout span span {
    background-image: none !important;
    background-position: 100% 0;
    color: #E26703;
    padding: 0 30px 8px 0;
}
	.level2-inactive {
    display: none !important;
}
.level2-active	{
	 display: none !important;
}
 </style>   
 <script language="javascript">
var tld_ = new Array()
tld_[0] = "au";
var topDom_ = 13;
var m_ = "mailto:";
var a_ = "@";
var d_ = ".";

function mail(name, dom, tl, params)
{
	var s = e(name,dom,tl);
	return '<a href="'+m_+s+params+'">'+s+'</a>';
}
function mail2(name, dom, tl, params, display)
{
	return '<a href="'+m_+e(name,dom,tl)+params+'">'+display+'</a>';
}

function e(name, dom, tl)
{
	var s = name+a_;
	if (tl!=-2)
	{
		s+= dom;
		if (tl>=0)
			s+= d_+tld_[tl];
	}
	else
		s+= swapper(dom);
	return s;
}
function swapper(d)
{
	var s = "";
	for (var i=0; i<d.length; i+=2)
		if (i+1==d.length)
			s+= d.charAt(i)
		else
			s+= d.charAt(i+1)+d.charAt(i);
	return s.replace(/\?/g,'.');
}


 jQuery(function(){
	 if(jQuery('.crosssell').length==0){

jQuery('html body.checkout-cart-index div.wrapper div.page div.main-container div.main div.col-main div.cart div.cart-collaterals div.col2-set div.col-2 div.shipping').attr('style','bottom: 330px ! important; left: 297px;');

jQuery('html body.checkout-cart-index div.wrapper div.page div.main-container div.main div.col-main div.cart div.cart-collaterals div.totals').attr('style','right: 668px !important; width: 258px !important;');
	 }
	 
	 
//email writes
sd=mail("admin","thebedroom.com",0,"","admin@thebedroom.com")	

jQuery('.xemail').html(sd); 
	 
jQuery('.btn-checkout').removeAttr('onclick','https://staging.thebedroom.com.au/onestepcheckout')


jQuery('.btn-checkout').click(function(){
window.location='https://staging.thebedroom.com.au/onestepcheckout'
});
	 
	 });
 </script>   