<div class="simple-forum-content">
<?php echo $this->getHeadHtml(); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getBreadCrumbs(); ?>
<?php echo $this->getTop(); ?>
<div class="forum-top">
<table width="100%">
	<tr>
		<td>
			<div class="forum-title">
				<?php echo $this->getTitleContent(); ?>
			</div>
		</td>
		<td>
			<div class="forum-controls">
				<?php echo $this->getControls(); ?>
			</div>
		</td>
	</tr>
</table>
</div>
<?php echo $this->getToolbarHtml(); ?>
<?php $topics = $this->getAllObjects(); ?>
<div>
    <table witdh="100%" border="0" id="forum_table" class="data-table">
		<thead>
		<tr class="first last">		
			<th width="40%"><?php echo $this->__('Topic Title') ?></th>			
			<th width="10%"><?php echo $this->__('Total Posts') ?></th>			
			<th width="10%"><?php echo $this->__('Views') ?></th>
			<th width="40%"><?php echo $this->__('Latest Reply') ?></th>
		<tr>
		</thead>
	<?php if($topics->getSize()): ?>
		<?php foreach($topics as $topic): ?>
		<tr>
			<td>
				<table width="100%" cellpadding="2" cellspacing="2">
						<tr>
							<td width="1%">
								<img src="<?php echo $this->getSkinUrl() ?>forum/images/folder_topic.png" >
							</td>
							<td style="border:0px;">
								<a id="simple-forum-link-<?php echo $topic->getId() ?>" href="<?php echo $this->getViewUrl( $topic->getId(), $topic);?>">
									<?php echo $topic->getTitle(); ?>
								</a>
							<?php if($topic->getDescription() && trim($topic->getDescription()) != ''): ?>
								<script>
									var ___tBaloon = new doBaloon($('simple-forum-link-<?php echo $topic->getId() ?>'), false, false, '<?php echo addslashes($topic->getDescription()) ?>');

								</script>
							<?php endif; ?>
								<br>
								<?php echo $this->__('Created') ?>: <?php echo $this->getFormatedDate($topic->getCreated_time());?><br>
								<?php echo $this->__('Created By') ?>: <?php echo $this->getCreateTopicUser($topic); ?>
							</td>
							<?php if($this->getHaveEditableRights($topic->getSystem_user_id())): ?>
							<td style="border:0px;">
								<div class="forum-controls-user">
									<nobr>
									<a href="<?php echo $this->getEditTopicUrl($topic->getId(), $topic); ?>">
										<img src="<?php echo $this->getSkinUrl('forum/images/page_edit.png') ?>" alt="<?php echo $this->__('Edit') ?>" title="<?php echo $this->__('Edit') ?>" border="0" /></a>
									<?php if($this->getAllowDelete()): ?>
									&nbsp;<a href="<?php echo $this->getDeleteTopicUrl($topic->getId()); ?>" onclick="if(confirm('<?php echo $this->__('Are You sure?') ?>')) document.location.href=this.href; return false;"><img src="<?php echo $this->getSkinUrl('forum/images/delete.png') ?>" border="0" alt="<?php echo $this->__('Delete') ?>" title="<?php echo $this->__('Delete') ?>" /></a>
									<?php endif; ?>
									<?php if($this->isModerator()): ?>
										<?php if($topic->getStatus() == 1): ?>
											&nbsp;<a href="<?php echo $this->getDeactivateTopicUrl($topic->getId()); ?>"><img src="<?php echo $this->getSkinUrl('forum/images/cancel.png') ?>" alt="<?php echo $this->__('Deactivate') ?>" title="<?php echo $this->__('Deactivate') ?>" border="0" /></a>
										<?php elseif($topic->getStatus() == 0): ?>
											&nbsp;<a href="<?php echo $this->getActivateTopicUrl($topic->getId()); ?>" ><img src="<?php echo $this->getSkinUrl('forum/images/add.png') ?>" alt="<?php echo $this->__('Activate') ?>" title="<?php echo $this->__('Activate') ?>" border="0" /></a>
										<?php endif; ?>
									<?php endif; ?>
									</nobr>
								</div>
							</td>
							<?php endif; ?>
						</tr>
					</table>
								
			</td>
			<td style="text-align:center;"><?php echo $topic->getTotal_posts();?></td>			
			<td style="text-align:center;"><?php echo $topic->getTotal_views();?></td>			
			<td>
				<?php if($topic->getLatest_topic()): ?>
					<a id="simple-forum-link-latest-<?php echo $topic->getLatest_topic()->getId() ?>" href="<?php echo $this->getViewUrlLatest( $topic->getLatest_postId(), $topic);?>"><?php echo $topic->getLatest_topic()->getTitle(); ?></a><br>
					<?php if($topic->getLatest_topic()->getDescription() && trim($topic->getLatest_topic()->getDescription()) != ''): ?>
								<script>
									var ___tBaloon = new doBaloon($('simple-forum-link-latest-<?php echo $topic->getLatest_topic()->getId() ?>'), false, false, '<?php echo addslashes($topic->getLatest_topic()->getDescription()) ?>');

								</script>
					<?php endif; ?>
					<?php echo $this->__('Posted'); ?> :<?php echo $this->getFormatedDate($topic->getLatest_created_time());?><br>
					<?php echo $this->__('Posted By'); ?> :<?php echo $this->getLatestReply($topic); ?>
				<?php else: ?>
					<?php echo $this->__('No Posts posted Yet'); ?>
				<?php endif; ?>
				
			</td>
		</tr>
		<?php endforeach; ?>

	<?php else: ?>
		<tr>
		<td colspan="4">
			<div style="text-align:center" class="forum-no-data-table">
				<?php echo $this->__('No Data To Display'); ?>
			</div>
		</td>
	</tr>
	<?php endif;?>
	</table>
<?php echo $this->getToolbarHtml(); ?>
	<br>
	<table width="100%">
	<tr>
		<td>
			<div class="forum-title">
				<?php echo $this->getTitleContent(); ?>
			</div>
		</td>
		<td>
			<div class="forum-controls">
				<?php echo $this->getControls(); ?>
			</div>
		</td>
	</tr>
</table>
</div>
</div>