<?php
/**
 * @category    design
 * @package     bedroom_default
 * @author      Anying Zhao
 */
?>
<table class="table-totals" cellpadding="0" cellspacing="0" border="0" style="width:100%;">
    <tr>
        <td class="padding-totals">
            <table cellpadding="0" cellspacing="0" border="0" style="width:100%;">
                <?php echo $this->getChildHtml(); ?>
            </table>
        </td>
    </tr>
</table>